feat: Readme
henriquefral/Socrates pull request #9
Opened 2021-11-29 19:28 UTC by Gessilt

2021-12-04 21:50 UTC, edigar requested changes
Achei um pouco verboso/filosófico, mas ok, é estilo 🤭 .

2021-12-04 21:50 UTC, edigar commented on README.md
> +O sócrates é um projeto construído em Laravel e Vue js para organização, com foco acadêmico. O Sócrates dá a possibilidade de organização, de forma fácil, para a vida de um aluno. Sejam benditos os e
```suggestion
O sócrates é um projeto construído em [Laravel](https://laravel.com/) e [Vue.js](https://vuejs.org/) para organização, com foco acadêmico. O Sócrates dá a possibilidade de organização, de forma fácil, para a vida de um aluno. Sejam benditos os eternos alunos da vida. Tem a intenção de armazenar: 
```

2021-12-04 21:50 UTC, edigar commented on README.md
> +- Lembretes de provas e;
```suggestion
- Lembretes de provas;
```

2021-12-04 21:50 UTC, edigar commented on README.md
> +- Banco de dados;
Trocaria esses dois primeiros itens para algo como "Ambiente para Laravel x.y", linkando com a documentação do Laravel para esses requisitos.

2021-12-04 21:50 UTC, edigar commented on README.md
> +- NPM;
Qual versão?

2021-12-04 21:50 UTC, edigar commented on README_laravel.md
> +<p align="center"><a href="https://laravel.com" target="_blank"><img src="https://raw.githubusercontent.com/laravel/art/master/logo-lockup/5%20SVG/2%20CMYK/1%20Full%20Color/laravel-logolockup-cmyk-re
Por que manter esse arquivo?

2021-12-05 15:17 UTC, Gessilt commented on README_laravel.md
> +<p align="center"><a href="https://laravel.com" target="_blank"><img src="https://raw.githubusercontent.com/laravel/art/master/logo-lockup/5%20SVG/2%20CMYK/1%20Full%20Color/laravel-logolockup-cmyk-re
Não queria jogar descartar. Mas não faz sentido, realmente.

2021-12-05 15:42 UTC, Gessilt commented on README.md
> +- Banco de dados;
```
Para que você utilize o Sócrates, precisará de:

- [Ambiente laravel](https://laravel.com/docs/7.x#installation);
```

2021-12-05 15:42 UTC, Gessilt commented on README.md
> +- NPM;
```suggestion
- [Ambiente Vue.js](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started#installation);
```

2021-12-05 15:45 UTC, Gessilt reviewed
Tudo de acordo

2021-12-05 15:45 UTC, Gessilt commented on README.md
> +- Banco de dados;
```suggestion
Para que você utilize o Sócrates, precisará de: 

- [Ambiente laravel](https://laravel.com/docs/7.x#installation);
```

2021-12-15 13:33 UTC, edigar requested changes
Você pode adicionar commits com as alterações e adicionar à essa branch (git push), que as alterações entram no PR. 😉

2021-12-15 13:33 UTC, edigar commented on README.md
> +- Banco de dados;
Laravel (com L em maiúsculo)

2021-12-15 13:33 UTC, edigar commented on README_laravel.md
> +<p align="center"><a href="https://laravel.com" target="_blank"><img src="https://raw.githubusercontent.com/laravel/art/master/logo-lockup/5%20SVG/2%20CMYK/1%20Full%20Color/laravel-logolockup-cmyk-re
Esse arquivo ainda permanece no repo.

2021-12-16 00:19 UTC, henriquefral commented
Alterações feitas, commit sobre a parte de requisitos e exclusão do readme desnecessário.

2021-12-16 13:08 UTC, edigar approved these changes
🚀

2021-12-17 00:26 UTC, merged